server:
  port: 8989

management:
  port: 8990

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    non-secure-port: ${PORT:8989}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
